services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/princejaiswalcoder/ERA_RENAME_BOT.git    
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: force_channel 
        sync: false
      - key: DB_NAME 
        sync: false
      - key: DB_URL 
        sync: false 
      - key: START_PIC 
        sync: false
      - key: ADMIN 
        sync: false    
    autoDeploy: false 
